#!/bin/bash

# setting the locale and timezone
ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf
# setting the tty keyboard
echo -e "keycode 1 = Caps_Lock\nkeycode 58 = Escape" > /usr/share/kbd/keymaps/caps-esc.map
echo -e "FONT=ter-122n\nKEYMAP=caps-esc" > /etc/vconsole.conf
# setting the hostname
echo "tblx" >> /etc/hostname
# setting the hosts file
echo -e "127.0.0.1    localhost\n::1          localhost\n127.0.1.1    tblx" >> /etc/hosts
# setting up doas
echo "permit nopass :wheel" >> /etc/doas.conf
# changing /bin/sh to dash
ln -sfT dash /usr/bin/sh
echo "[Trigger]
Type = Package
Operation = Install
Operation = Upgrade
Target = bash

[Action]
Description = Re-pointing /bin/sh symlink to dash...
When = PostTransaction
Exec = /usr/bin/ln -sfT dash /usr/bin/sh
Depends = dash" > /usr/share/libalpm/hooks/dashbinsh.hook
# setting doas as sudo symlink
ln -sfT /bin/doas /bin/sudo
# setting font
echo -e "<match target="pattern">
  <test qual="any" name="family"><string>monospace</string></test>
  <edit name="family" mode="assign" binding="same"><string>Iosevka Nerd Font</string></edit>
</match>
" >> /etc/fonts/fonts.conf
# setting up systemd-boot
bootctl install
echo -e "default arch.conf\ntimeout 0" > /boot/loader/loader.conf
echo -e "title   Arch Linux\nlinux   /vmlinuz-linux-zen\ninitrd  /intel-ucode.img\ninitrd  /initramfs-linux-zen.img\noptions root=\"LABEL=Arch\" resume=\"LABEL=Swap\" rw" > /boot/loader/entries/arch.conf
# setting ZDOTDIR
# echo "ZDOTDIR=/home/siki/.config/zsh" >> /etc/environment
# enabling networkmanager and cronie
systemctl enable NetworkManager
systemctl enable cronie.service
# adding the user and assigning groups
useradd -m siki -G wheel,audio,video,storage,optical
# setting my mkinitcpio for hibernate feature
sed -e 's/^HOOKS.*/HOOKS=(base udev autodetect keyboard modconf block filesystems resume fsck)/' -e 's/vim.*/vim:ft=sh/' -i /etc/mkinitcpio.conf
mkinitcpio -p linux-zen
# downloading post post install script and putting it in home folder of user
curl -L https://github.com/si-ki/autoarch/raw/master/postpost > /home/siki/postpost
# running the script as the user
su -c "sh /home/siki/postpost" siki
# changing the default shell of user to zsh
chsh siki -s /bin/zsh
# cleanup
rm -rf /home/siki/{.bash_history,.bash_profile,.bash_logout,.bashrc}
