#!/bin/bash
# making directories
mkdir -p ~/dwn ~/vid ~/pix ~/doc ~/.cache/zsh
# settings up dots
alias dot='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
echo ".cfg" >> .gitignore
git clone --bare https://github.com/si-ki/dotfiles.git ~/.cfg
alias dot='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
dot checkout

# cloning the scripts repo to ~/.local
git clone https://github.com/si-ki/bin.git ~/.local/bin

# setting up the origin for push
cd ~/.cfg
git remote set-url origin git@github.com:si-ki/dotfiles
cd ~/.local/bin
git remote set-url origin git@github.com:si-ki/bin
cd ~/doc/autoarch
git remote set-url origin git@github.com:si-ki/autoarch
