#!/bin/sh

# Setting the tty font
setfont ter-122n

# Changing some settings in pacman.conf(5)
sed -e 's/CheckSpace/#CheckSpace/' -e 's/#ParallelDownloads\ =\ 5/ParallelDownloads = 10\nILoveCandy/' -e 's/#Color/Color/' -e 's/#VerbosePkgLists/VerbosePkgLists/' -i /etc/pacman.conf

# pulling down good mirrors
reflector --country China,India --latest 20 --sort rate --save /etc/pacman.d/mirrorlist

# preparing the disks
mkfs.fat -F32 /dev/sda1
mkswap /dev/sda2 -L "Swap"
yes | mkfs.ext4 /dev/sda3 -L "Arch"
yes | mkfs.ext4 /dev/sda4
mount /dev/sda3 /mnt
mkdir /mnt/{boot,home}
mount /dev/sda1 /mnt/boot
mount /dev/sda4 /mnt/home
swapon /dev/sda2

# installing the base system
pacstrap /mnt intel-ucode base hyprland git linux-zen linux-zen-headers linux-firmware neovim networkmanager opendoas wireplumber pipewire pipewire-pulse pulsemixer openssh imv terminus-font ttf-jetbrains-mono-nerd man-pages wl-clipboard zathura-pdf-mupdf make pkgconf ttf-joypixels dunst ffmpeg yt-dlp zip unzip mpv dash gcc foot zsh bat patch ttf-iosevka-nerd firefox fzf lf

# generating the fstab file
genfstab -U /mnt >> /mnt/etc/fstab

# putting the mirrorlist to system so that i don't need to run it again
cp -f /etc/pacman.d/mirrorlist /mnt/etc/pacman.d/mirrorlist

# downloading and putting the post chroot script to /mnt
curl -L https://github.com/si-ki/autoarch/raw/master/post > /mnt/post

# running post chroot script inside of /mnt
arch-chroot /mnt sh post

# cleanup
rm -rf /mnt/post

# rebooting the system
echo "you may now reboot"
